name: build-windows-exe

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - ".github/workflows/build-windows.yml"
      - "windows/**"
      - "data/**"
      - "README.md"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --onefile --name bulk_mailer src/main.py

      - name: Copy runtime assets
        shell: bash
        run: |
          mkdir -p upload/data
          mkdir -p upload/windows
          cp -R data/* upload/data/ || true
          cp -R windows/* upload/windows/ || true
          cp -R dist/bulk_mailer.exe upload/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bulk_mailer_windows
          path: upload/**
          if-no-files-found: error
